server:
  port: 8090

spring:
  h2:
    console:
      enabled: true
  datasource:
#     url: jdbc:log4jdbc:mariadb://localhost:3306/springweb02
#     url: jdbc:log4jdbc:h2:mem:springweb;MODE=MySQL;DB_CLOSE_DELAY=-1
     url: jdbc:log4jdbc:h2:file:./h2db/springweb;AUTO_SERVER=TRUE;MODE=MySQL;
     driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
     username: sa
     password: 
#     dbcp2:
#      validation-query: SELECT 1
  jpa:
#     generate-ddl: true
     hibernate:
      ddl-auto: none
     show-sql: true
     properties:
      hibernate:
        format_sql: true
  devtools:
    livereload:
      enabled: true
  data:
    rest:
      base-path: api
      

security:
  jwt:
    key-store: classpath:server.jks
    key-store-password: 123456
    key-pair-alias: server_private
    key-pair-password: 123456
    public-key: classpath:public.txt
          
              
                