GET http://localhost:9999/spring-admin/api/users
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjUwNjg3MDUsInVzZXJfbmFtZSI6ImFkbWluIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiJdLCJqdGkiOiIzNDg1NjRiOC0wMGMwLTQ2ZDgtOTcwOS0yMWY2MjEzMDIyNDYiLCJjbGllbnRfaWQiOiJzcHJpbmciLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiLCJ0cnVzdCJdfQ.fjCXP40McAB1V_Zg3-qY5itI3uPQsRBp-e4w8rvwwqhon4GO7Afy97bnmo38W5AOD_TmbduNOvrfsB4yYC2swN7ttlq8rwo2UQxG5uvGKcK65wucUYdA2HimXsZpCry-p09rLm1UVREV61xgnxJNHMEed63OXSEZa7GwaKwBY5vJAaGxRam1_fyV1lqTy8U8e_ZKNgri08_U_p5UCmViwM6X2tfaSYraeMpZEj2sqtisYuo_Wz3TzAH3mvH4aHix2O2ercbd2yM8ZM4BWXQhP5FLuKqh8-_nlwB96_OSUaf63-awI5hNH17g0COsIKi0-PB2opVARe4ICFFA66E3Ug

###
// jwt 토큰 확인
POST http://localhost:9999/oauth/check_token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic spring 1234

token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MjUwNjg3MDUsInVzZXJfbmFtZSI6ImFkbWluIiwiYXV0aG9yaXRpZXMiOlsiUk9MRV9BRE1JTiJdLCJqdGkiOiIzNDg1NjRiOC0wMGMwLTQ2ZDgtOTcwOS0yMWY2MjEzMDIyNDYiLCJjbGllbnRfaWQiOiJzcHJpbmciLCJzY29wZSI6WyJyZWFkIiwid3JpdGUiLCJ0cnVzdCJdfQ.fjCXP40McAB1V_Zg3-qY5itI3uPQsRBp-e4w8rvwwqhon4GO7Afy97bnmo38W5AOD_TmbduNOvrfsB4yYC2swN7ttlq8rwo2UQxG5uvGKcK65wucUYdA2HimXsZpCry-p09rLm1UVREV61xgnxJNHMEed63OXSEZa7GwaKwBY5vJAaGxRam1_fyV1lqTy8U8e_ZKNgri08_U_p5UCmViwM6X2tfaSYraeMpZEj2sqtisYuo_Wz3TzAH3mvH4aHix2O2ercbd2yM8ZM4BWXQhP5FLuKqh8-_nlwB96_OSUaf63-awI5hNH17g0COsIKi0-PB2opVARe4ICFFA66E3Ug

###
// jwt 토큰 요청
POST http://localhost:9999/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic spring 1234

isManager=Y&grant_type=password&username=admin&password=1234

###

